#!/bin/bash

# Variables
vim_server_name=`echo ${PWD##*/} | tr '[:lower:]' '[:upper:]'`

# Collate all the files
collate_file_list()
{
	if [ -f temp_file_list ]; then rm temp_file_list; fi
	if [ $# -gt 0 ]; then
		for arg in "$@"
		do
			find $arg -regex '.*\.\(c\|cpp\|h\|hpp\|inl\)$' >> temp_file_list
		done
	else
		find -regex '.*\.\(c\|cpp\|h\|hpp\|inl\)$' >> temp_file_list
	fi

	# Remove any temporary .swp files from crashed vim instances
	for file in `cat temp_file_list`
	do
		if [ -f ${file%/*}/.${file##*/}.swp ]; then
		 	echo Removing old swap file for $file...
			rm ${file%/*}/.${file##*/}.swp
		fi
	done
}

tidy_up()
{
	if [ -f temp_file_list ]; then rm temp_file_list; fi
}

# Main script
collate_file_list $@

# Open them in vim (N.B. remember to set tabpagemax to 999 or you'll only get 10
# tabs max by default and the rest of the files will be split windows)
echo Sending files to $vim_server_name.GVIM instance...
gvim --servername $vim_server_name.GVIM --remote-tab-silent `cat temp_file_list` &

tidy_up

