#!/bin/bash

# Variables
vim_server_exists=false
vim_server_name=`echo ${PWD##*/} | tr '[:lower:]' '[:upper:]'`

# Function to check for the vim server
check_vim_server_exists()
{
	for server in `vim --serverlist`
	do
		if [ $server = $vim_server_name ]; then
			vim_server_exists=true
			return
		fi
	done
}

# Start gvim in server mode, if it doesn't already exist
echo Checking for $vim_server_name server...
check_vim_server_exists

if [ $vim_server_exists = false ]; then
	echo Starting $vim_server_name server...
 	gvim --servername $vim_server_name &
fi

while [ $vim_server_exists = false ]; do
	echo ...waiting for $vim_server_name server to start...
	sleep 1
	check_vim_server_exists
done

echo ...$vim_server_name server started.

# Collate all the files
if [ -f temp_file_list ]; then rm temp_file_list; fi
if [ $# -gt 0 ]; then
	for arg in "$@"
	do
		find $arg -name '*.cpp' >> temp_file_list
		find $arg -name '*.h' >> temp_file_list
	done
else
		find -name '*.cpp' >> temp_file_list
		find -name '*.h' >> temp_file_list
fi

# Sort them...
if [ -f sorted_file_list ]; then rm sorted_file_list; fi
sort temp_file_list > sorted_file_list

# Open them in vim
echo Opening...
cat sorted_file_list | while read arg; do
	echo [$arg]
	gvim --servername $vim_server_name --remote-tab $arg
done
echo ...done.

# Tidy up
rm temp_file_list
rm sorted_file_list

