#!/bin/bash

########################################
# Make scripts
make_script_stub()
{
	echo "#!/bin/bash" > $1
	echo "config=debug" >> $1
	echo "if [ \$# -gt 0 ]; then" >> $1
	echo "	case \$1 in" >> $1
	echo "		[dD][eE][bB][uU][gG]) shift; config=debug ;;" >> $1
	echo "		[rR][eE][lL][eE][aA][sS][eE]) shift; config=release ;;" >> $1
	echo "	esac" >> $1
	echo "fi" >> $1
	echo "echo [\$config] \$@" >> $1
}

make_scripts()
{
	# utility script to run make from project root
	make_script_stub "make"
	echo "cd build/$1\$config" >> make
	echo "make \$@" >> make

	# utility script to run the build from project root
	make_script_stub "run"
	echo "build/$1\$config/test \$@" >> run

	# utility script to run the unit tests from project root
	make_script_stub "unit-test"
	echo "build/$1\$config/unit-test --log unit-test.log \$@" >> unit-test
}
#
########################################

########################################
# Windows bit
update_windows()
{
	if [ ! -d build ]; then mkdir -p build/msys/{debug,release}; fi

	cd build/msys/debug
	echo Updating MSYS debug build environment...
	cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Debug ../../..
	cd ../release
	echo Updating MSYS release build environment...
	cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release ../../..
	cd ../..

	if [ ! -d vs ]; then mkdir vs; fi
	cd vs

	echo Updating Visual Studio build environment...
	cmake -G "Visual Studio 10 Win64" ../..
	cd ../..

	make_scripts "msys/"

	return
}
#
########################################

########################################
# Linux bit
update_linux()
{
	if [ ! -d build ]; then mkdir -p build/{debug,release}; fi

	cd build/debug
	echo Updating Linux debug build environment...
	cmake -DCMAKE_BUILD_TYPE=Debug ../..
	cd ../release
	echo Updating Linux release build environment...
	cmake -DCMAKE_BUILD_TYPE=Release ../..
	cd ../..

	make_scripts

	chmod +x make run unit-test

	return
}
#
########################################

case $1 in
[wW][iI][nN]) update_windows ;;
[wW][iI][nN][dD][oO][wW][sS]) update_windows ;;
[lL][iI][nN]) update_linux ;;
[lL][iI][nN][uU][xX]) update_linux ;;
*) echo "Invalid option [$1]"; exit ;;
esac

echo Build environment updated.

