#!/bin/bash

########################################
# Windows bit
update_windows()
{
	if [ ! -d build ]; then mkdir -p build/msys/{debug,release}; fi

	cd build/msys/debug
	echo Updating MSYS debug build environment...
	cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Debug ../../..
	cd ../release
	echo Updating MSYS release build environment...
	cmake -G "MSYS Makefiles" -DCMAKE_BUILD_TYPE=Release ../../..
	cd ../..

	if [ ! -d vs ]; then mkdir vs; fi
	cd vs

	echo Updating Visual Studio build environment...
	cmake -G "Visual Studio 10 Win64" ../..
	cd ../..

	# utility script to run make from project root
	echo "#!/bin/bash" > make
	echo "config=debug" >> make
	echo "if [ \$# -gt 0 ]; then" >> make
	echo "	case \$1 in" >> make
	echo "		[dD][eE][bB][uU][gG]) shift; config=debug ;;" >> make
	echo "		[rR][eE][lL][eE][aA][sS][eE]) shift; config=release ;;" >> make
	echo "	esac" >> make
	echo "fi" >> make
	echo "echo [\$config] \$@" >> make
	echo "cd build/msys/\$config" >> make
	echo "make \$@" >> make

	# utility script to run the build from project root
	echo "#!/bin/bash" > run
	echo "config=debug" >> run
	echo "if [ \$# -gt 0 ]; then" >> run
	echo "	case \$1 in" >> run
	echo "		[dD][eE][bB][uU][gG]) shift; config=debug ;;" >> run
	echo "		[rR][eE][lL][eE][aA][sS][eE]) shift; config=release ;;" >> run
	echo "	esac" >> run
	echo "fi" >> run
	echo "echo [\$config] \$@" >> run
	echo "build/msys/\$config/test \$@" >> run

	# utility script to run the unit tests from project root
	echo "#!/bin/bash" > "unit-test"
	echo "config=debug" >> "unit-test"
	echo "if [ \$# -gt 0 ]; then" >> "unit-test"
	echo "	case \$1 in" >> "unit-test"
	echo "		[dD][eE][bB][uU][gG]) shift; config=debug ;;" >> "unit-test"
	echo "		[rR][eE][lL][eE][aA][sS][eE]) shift; config=release ;;" >> "unit-test"
	echo "	esac" >> "unit-test"
	echo "fi" >> "unit-test"
	echo "echo [\$config] \$@" >> "unit-test"
	echo "build/msys/\$config/unit-test \$@" >> "unit-test"

	return
}
#
########################################

########################################
# Linux bit
update_linux()
{
	if [ ! -d build ]; then mkdir -p build/{debug,release}; fi

	cd build/debug
	echo Updating Linux debug build environment...
	cmake -DCMAKE_BUILD_TYPE=Debug ../..
	cd ../release
	echo Updating Linux release build environment...
	cmake -DCMAKE_BUILD_TYPE=Release ../..
	cd ../..

	# utility script to run make from project root
	echo "#!/bin/bash" > make
	echo "config=debug" >> make
	echo "if [ \$# -gt 0 ]; then" >> make
	echo "	case \$1 in" >> make
	echo "		[dD][eE][bB][uU][gG]) shift; config=debug ;;" >> make
	echo "		[rR][eE][lL][eE][aA][sS][eE]) shift; config=release ;;" >> make
	echo "	esac" >> make
	echo "fi" >> make
	echo "echo [\$config] \$@" >> make
	echo "cd build/\$config" >> make
	echo "make \$@" >> make

	# utility script to run the build from project root
	echo "#!/bin/bash" > run
	echo "config=debug" >> run
	echo "if [ \$# -gt 0 ]; then" >> run
	echo "	case \$1 in" >> run
	echo "		[dD][eE][bB][uU][gG]) shift; config=debug ;;" >> run
	echo "		[rR][eE][lL][eE][aA][sS][eE]) shift; config=release ;;" >> run
	echo "	esac" >> run
	echo "fi" >> run
	echo "echo [\$config] \$@" >> run
	echo "build/\$config/test \$@" >> run

	# utility script to run the unit tests from project root
	echo "#!/bin/bash" > "unit-test"
	echo "config=debug" >> "unit-test"
	echo "if [ \$# -gt 0 ]; then" >> "unit-test"
	echo "	case \$1 in" >> "unit-test"
	echo "		[dD][eE][bB][uU][gG]) shift; config=debug ;;" >> "unit-test"
	echo "		[rR][eE][lL][eE][aA][sS][eE]) shift; config=release ;;" >> "unit-test"
	echo "	esac" >> "unit-test"
	echo "fi" >> "unit-test"
	echo "echo [\$config] \$@" >> "unit-test"
	echo "build/\$config/unit-test \$@" >> "unit-test"

	chmod +x make run unit_test

	return
}
#
########################################

case $1 in
[wW][iI][nN]) update_windows ;;
[wW][iI][nN][dD][oO][wW][sS]) update_windows ;;
[lL][iI][nN]) update_linux ;;
[lL][iI][nN][uU][xX]) update_linux ;;
*) echo "Invalid option [$1]"; exit ;;
esac

echo Build environment updated.

