#!/bin/bash

########################################
# Windows bit
update_windows()
{
	if [ ! -d msys ]; then mkdir msys; fi
	cd msys

	echo Updating MSYS build environment...
	cmake -G "MSYS Makefiles" ../..
	cd ..

	if [ ! -d vs ]; then mkdir vs; fi
	cd vs

	echo Updating Visual Studio build environment...
	cmake ../..
	cd ../..

	# utility script to run make from project root
	echo "#!/bin/bash" > make
	echo "cd build/msys" >> make
	echo "make" >> make

	return
}
#
########################################

########################################
# Linux bit
update_linux()
{
	echo Updating Linux build environment...
	cmake ..
	cd ..

	# utility script to run make from project root
	echo "#!/bin/bash" > make
	echo "cd build" >> make
	echo "make" >> make

	return
}
#
########################################

if [ ! -d build ]; then mkdir build; fi
cd build

case $1 in
[wW]) update_windows ;;
[wW][iI][nN]) update_windows ;;
[wW][iI][nN][dD][oO][wW][sS]) update_windows ;;
[lL]) update_linux ;;
[lL][iI][nN]) update_linux ;;
[lL][iI][nN][uU][xX]) update_linux ;;
*) echo "Invalid option [$1]"; exit ;;
esac

echo Build environment updated.

